<a href="https://colab.research.google.com/github/Amrutha-Tsavatapalli/ACM-work/blob/main/task4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
# Create two random tensors of shape 3x3
A = torch.randn(3, 3, requires_grad=True)
B = torch.randn(3, 3)
# Perform matrix multiplication
C = torch.matmul(A, B)
# Compute the gradient of C w.r.t. A
C.sum().backward()
# Print tensors and gradients
print("Tensor A:\n", A)
print("\nTensor B:\n", B)
print("\nResult C:\n", C)
print("\nGradient of C w.r.t. A:\n", A.grad)
## Matrix Multiplication and Autograd


Tensor A:
 tensor([[-0.6426,  0.2794,  0.5881],
        [-1.2952,  0.1035,  1.7633],
        [ 0.1025,  1.2268,  0.3110]], requires_grad=True)

Tensor B:
 tensor([[ 0.0017, -0.1432, -0.6097],
        [-0.2743, -1.3478,  0.3128],
        [-0.8819,  0.0809, -0.8218]])

Result C:
 tensor([[-0.5964, -0.2369, -0.0041],
        [-1.5856,  0.1886, -0.6269],
        [-0.6105, -1.6430,  0.0656]], grad_fn=<MmBackward0>)

Gradient of C w.r.t. A:
 tensor([[-0.7513, -1.3093, -1.6229],
        [-0.7513, -1.3093, -1.6229],
        [-0.7513, -1.3093, -1.6229]])


In [2]:
# Create a 3x1 tensor and a 1x3 tensor
X = torch.randn(3, 1)
Y = torch.randn(1, 3)
# Add using broadcasting
Z = X + Y
# Multiply by another 3x3 tensor
M = torch.randn(3, 3)
result = Z * M
# Print results
print("\nTensor X (3x1):\n", X)
print("\nTensor Y (1x3):\n", Y)
print("\nBroadcasted Addition (3x3):\n", Z)
print("\nFinal Result (3x3):\n", result)
##Broadcasting


Tensor X (3x1):
 tensor([[ 0.2188],
        [ 1.1846],
        [-0.6666]])

Tensor Y (1x3):
 tensor([[ 0.8973,  0.0440, -0.4861]])

Broadcasted Addition (3x3):
 tensor([[ 1.1161,  0.2628, -0.2673],
        [ 2.0819,  1.2286,  0.6985],
        [ 0.2307, -0.6226, -1.1527]])

Final Result (3x3):
 tensor([[ 1.0214,  0.0607, -0.3973],
        [ 1.1718, -0.6274, -1.2913],
        [ 0.2118, -0.1120, -2.6630]])


In [3]:
# Create a (6,4) tensor
T = torch.randn(6, 4)
# Reshape it to (3,8)
T_reshaped = T.view(3, 8)
# Extract the first two columns (all rows)
slice_T = T_reshaped[:, :2]
# Print results
print("\nOriginal Tensor (6x4):\n", T)
print("\nReshaped Tensor (3x8):\n", T_reshaped)
print("\nExtracted Slice (first two columns):\n", slice_T)
##Reshaping and Slicing


Original Tensor (6x4):
 tensor([[ 0.6951, -1.1115, -0.0037,  1.3299],
        [-0.3312,  2.1172,  0.9511, -1.3527],
        [ 2.5903,  1.3408, -1.4696,  0.8051],
        [-2.0450, -0.8795, -0.1838,  1.4640],
        [-0.0401,  0.2433,  1.6943, -2.0780],
        [-0.1609, -1.0725, -0.9030,  0.1014]])

Reshaped Tensor (3x8):
 tensor([[ 0.6951, -1.1115, -0.0037,  1.3299, -0.3312,  2.1172,  0.9511, -1.3527],
        [ 2.5903,  1.3408, -1.4696,  0.8051, -2.0450, -0.8795, -0.1838,  1.4640],
        [-0.0401,  0.2433,  1.6943, -2.0780, -0.1609, -1.0725, -0.9030,  0.1014]])

Extracted Slice (first two columns):
 tensor([[ 0.6951, -1.1115],
        [ 2.5903,  1.3408],
        [-0.0401,  0.2433]])
